tweetme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from tweets.views import TweetListView
from tweets.api.views import SearchAPIView

from hashtags.views import HashTagView
from hashtags.api.views import HashTagAPIView

from .views import (
    UserLoginView,
    UserLogoutView,
    SearchView,
    TermsView,
    ContactFormView,
)


urlpatterns = [
    path('', TweetListView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('tweet/', include('tweets.urls', namespace='tweet')),
    path('register/', include('register.urls', namespace='register')),
    path('search/', SearchView.as_view(), name='search'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profiles/', include('accounts.urls', namespace='profiles')),
    path('api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    path('api/search/',SearchAPIView.as_view(), name='search-api'),
    path('api/tag/<str:hashtag>/',HashTagAPIView.as_view(), name='tag-api'),
    path('api/profiles/', include('accounts.api.urls', namespace='profile-api')),
    path('tags/<str:hashtag>/', HashTagView.as_view(), name='hashtag'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/api/urls.py
from django.urls import path

from .views import(TweetListAPIView,
                   TweetCreateAPIView,
                   RetweetAPIView,
                   LikeTweetAPIView,
                   TweetDetailView
                   )

app_name = 'tweets'


urlpatterns = [
    path('', TweetListAPIView.as_view(), name='list'),  # /api/tweet/
    path('create/', TweetCreateAPIView.as_view(), name='create'),  # /api/tweet/create/
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),  # /api/tweet/pk/tweet
    path('<int:pk>/retweet/', RetweetAPIView.as_view(), name='retweet'),  # /api/tweet/pk/tweet
    path('<int:pk>/liked/', LikeTweetAPIView.as_view(), name='liked'),  # /api/tweet/pk/tweet
]

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    TweetDetailView,
    TweetListView,
    TweetCreateView,
    # TweetUpdateView,
    TweetDeleteView,
    RetweetView,
)

app_name = 'tweets'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/update/', TweetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TweetDeleteView.as_view(), name='delete'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),

]

tweets/models.py
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse_lazy
from django.conf import settings
from django.db import models


from accounts.models import UserProfile

User = get_user_model()


class TweetManager(models.Manager):
    def retweet(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj

        qs = self.get_queryset().filter(
            user=user, parent=og_parent
            ).filter(
                timestamp__year=now().year,
                timestamp__month=now().month,
                timestamp__day=now().day
            )

        if qs.exists():
            return None

        obj = self.model(
            parent=og_parent,
            user=user,
            content=og_parent.content
        )
        obj.save()
        return obj

    def like_toggle(self, user, tweet_obj):
        if user in tweet_obj.liked.all():
            is_liked = False
            tweet_obj.liked.remove(user)
        else:
            is_liked = True
            tweet_obj.liked.add(user)
        return is_liked


class Tweet(models.Model):
    parent      = models.ForeignKey('self',
                                    blank=True,
                                    null=True,
                                    on_delete=models.CASCADE
                                    )
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.CASCADE,
                                    )
    liked       = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                         blank=True,
                                         related_name='liked')
    content     = models.CharField(max_length=320)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    objects = TweetManager()

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse_lazy('tweet:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-timestamp']

tweets/forms.py
from django import forms

from .models import Tweet


class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label="",
                              widget=forms.Textarea(
                                  attrs={'placeholder': 'Que fuego deseas iniciar?',
                                         'class': 'form-control'}))

    class Meta:
        model = Tweet
        fields = [
            'content'
        ]

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) > 320:
            raise forms.ValidationError("Muy largo")
        return content

tweets/api/views.py
from rest_framework.generics import ListAPIView, CreateAPIView, RetrieveAPIView
from rest_framework.views import APIView
from  rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.db.models import Q

from .pagination import StandardResultsPagination
from .serializers import TweetModelSerializer
from tweets.models import Tweet


class LikeTweetAPIView(APIView):
    permission_classes      = [IsAuthenticated]

    def get(self, request, pk):
        tweet_qs = Tweet.objects.filter(pk=pk)
        is_liked = Tweet.objects.like_toggle(request.user, tweet_qs.first())
        return Response({"liked": is_liked})


class RetweetAPIView(APIView):
    permission_classes      = [IsAuthenticated]

    def get(self, request, pk):
        tweet_qs = Tweet.objects.filter(pk=pk)
        if tweet_qs.exists() and tweet_qs.count() == 1:
            new_tweet = Tweet.objects.retweet(request.user, tweet_qs.first())
            if new_tweet is not None:
                data = TweetModelSerializer(new_tweet).data
                return Response(data)
        return Response({'message': 'No esta Autorizado'}, status=400)


class TweetDetailView(RetrieveAPIView):
    queryset                = Tweet.objects.all()
    serializer_class        = TweetModelSerializer
    permission_classes      = [IsAuthenticated]


class TweetCreateAPIView(CreateAPIView):
    serializer_class        = TweetModelSerializer
    permission_classes      = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class TweetListAPIView(ListAPIView):
    serializer_class        = TweetModelSerializer
    pagination_class        = StandardResultsPagination

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['user'] = self.request.user
        return context

    def get_queryset(self):
        requested_user = self.kwargs.get("username")
        if requested_user:
            qs = Tweet.objects.filter(user__username=requested_user).order_by('-timestamp')
        else:
            my_followers = self.request.user.profile.get_following()
            qs1 = Tweet.objects.filter(user__in=my_followers).order_by('-timestamp')
            qs2 = Tweet.objects.filter(user=self.request.user)
            qs = (qs1 | qs2).distinct().order_by('-timestamp')
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs


class SearchAPIView(ListAPIView):
    serializer_class        = TweetModelSerializer
    pagination_class        = StandardResultsPagination

    def get_queryset(self):
        qs = Tweet.objects.all().order_by("-timestamp")
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib import messages

from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    View
)

from .models import Tweet
from .forms import TweetModelForm
from .mixins import FormUserNeededMixin, UserOwnerMixin


class RetweetView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=pk)
        Tweet.objects.retweet(request.user, tweet)
        return redirect('home')


class TweetCreateView(LoginRequiredMixin, FormUserNeededMixin, CreateView):
    template_name   = 'tweets/create_view.html'
    model           = Tweet
    form_class      = TweetModelForm


class TweetUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    template_name   = 'tweets/update_view.html'
    model           = Tweet
    form_class      = TweetModelForm


class TweetDeleteView(LoginRequiredMixin, DeleteView):
    template_name   = 'tweets/delete_view.html'
    model           = Tweet
    success_url     = reverse_lazy('home')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return redirect(success_url)
        else:
            messages.add_message(request, messages.ERROR, "No puedes borrar el contenido de los demas")
            return redirect('home')


class TweetDetailView(LoginRequiredMixin, DetailView):
    template_name   = 'tweets/detail_view.html'
    model           = Tweet


class TweetListView(LoginRequiredMixin, ListView):
    template_name   = 'tweets/list_view.html'
    model           = Tweet

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = TweetModelForm()
        context['create_url'] = reverse_lazy('tweet:create')
        return context

tweets/templates/tweets/create_view.html
{% extends 'base.html' %}

{% block title %}Nuevo | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-7 col-12">
            <h1>Nueva Fuego</h1>
            {% include 'tweets/form.html' with form=form btn_title='Leña'%}
        </div>
    </div>


{% endblock %}

tweets/templates/tweets/delete_view.html
{% extends 'base.html' %}

{% block title %}Borrar | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-7 col-12">
            <form method="post">{% csrf_token %}
                <p>Esta seguro que desea borrar <b>"{{ object.content }}"?</b></p>
            <button class="btn btn-danger" type="submit">Confirmar</button>
            </form>
        </div>
    </div>

{% endblock %}

tweets/templates/tweets/detail_view.html
{% extends 'base.html' %}

{% block script %}
<script>
$(document).ready(function () {
    loadTweetContainer("tweet-container", {{ object.id }})
})
</script>
{% endblock %}

{% block title %}Leña | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-3 col-12">
            <h1>{{ object.user }}</h1>
        </div>
        <div class="col-lg-7 col-12">
            <div id="tweet-container">

            </div>
            <a href="{% url 'tweet:delete' object.pk %}">Borrar?</a>
        </div>
    </div>

{% endblock %}

tweets/templates/tweets/form.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

<form {% if form_id %} id="{{ form_id }}" {% endif %}
        method="POST"
        class="form"
        action="{% if action_url %}{{ action_url }}{% endif %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="{{ btn_title }}">
</form>

tweets/templates/tweets/list_view.html
{% extends 'base.html' %}

{% block script %}

    <script>

    $(document).ready(function () {
        loadTweetContainer("tweet-container");
    });

    </script>

{% endblock %}

{% block title %}Actividad | {{ block.super }}{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for message in messages %}
                <strong>Oh no! </strong>{{ message|escape }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="row mt-2" id="row1">
        <div class="col-lg-3 col-12 my-4">
            <h2>{{ request.user }}</h2>
        </div>
        <div class="col-lg-7 col-12">
            {% if not request.GET.q %}
                {% include 'tweets/form.html' with form_id='tweet-form' form=create_form action_url=create_url btn_title='Leña' %}
                <hr/>
            {% endif %}
            <div id="tweet-container" data-url="/api/tweet/">

            </div>
            <a href="#" id="loadMore">cenizas..</a>
            <br/>
        </div>
    </div>

{% endblock %}

tweets/templates/tweets/search_form.html
<form id="navbar-search-form" class="form-inline  my-2 my-lg-0" method="GET" action="{% url 'search' %}">
    <label>
        <input class="form-control mr-sm-2" type="text" name="q" value="{{ request.GET.q }}">
    </label>
    <button class="btn btn-outline-success my-2 my-lg-0" type="submit">Buscar</button>
</form>

tweets/templates/tweets/update_view.html
{% extends 'base.html' %}

{% block title %}Actualizar | {{ block.super }}{% endblock %}

{% block content %}

{% include 'tweets/form.html' with form=form btn_title='Actualizar'%}

{% endblock %}