accounts/urls.py
from django.urls import path

from .views import UserDetailView, UserFollowView, user_update_view, FollowerView, FollowingView

app_name = 'accounts'

urlpatterns = [
    path('<slug:username>/', UserDetailView.as_view(), name='detail'),
    path('<slug:username>/followers/', FollowerView.as_view(), name='followers'),
    path('<slug:username>/following/', FollowingView.as_view(), name='following'),
    path('<slug:username>/edit/', user_update_view, name='edit'),
    path('<slug:username>/follow/', UserFollowView.as_view(), name='follow'),
]

register/urls.py
from django.urls import path

from .views import (
    RegisterView,
    ThanksForRegistering,
    UserChangePassword,
    UserChangePasswordDone,
    UserPasswordReset,
    UserPasswordResetDone,
    UserPasswordResetConfirmView,
    UserPasswordResetCompleteView
)

app_name = 'register'

urlpatterns = [
    path('', RegisterView.as_view(), name='start'),
    path('done/', ThanksForRegistering.as_view(), name='done'),
    path('password-change/', UserChangePassword.as_view(), name='password_change'),
    path('password-change/done/', UserChangePasswordDone.as_view(), name='password_change_done'),
    path('reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('reset/done/', UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-confirm/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

tweetme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from tweets.views import TweetListView
from tweets.api.views import SearchAPIView

from hashtags.views import HashTagView
from hashtags.api.views import HashTagAPIView

from .views import (
    UserLoginView,
    UserLogoutView,
    SearchView,
    TermsView,
    ContactFormView,
)


urlpatterns = [
    path('', TweetListView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('tweet/', include('tweets.urls', namespace='tweet')),
    path('register/', include('register.urls', namespace='register')),
    path('search/', SearchView.as_view(), name='search'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profiles/', include('accounts.urls', namespace='profiles')),
    path('api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    path('api/search/',SearchAPIView.as_view(), name='search-api'),
    path('api/tag/<str:hashtag>/',HashTagAPIView.as_view(), name='tag-api'),
    path('api/profiles/', include('accounts.api.urls', namespace='profile-api')),
    path('tags/<str:hashtag>/', HashTagView.as_view(), name='hashtag'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    TweetDetailView,
    TweetListView,
    TweetCreateView,
    # TweetUpdateView,
    TweetDeleteView,
    RetweetView,
)

app_name = 'tweets'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/update/', TweetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TweetDeleteView.as_view(), name='delete'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),

]

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django.contrib.auth import get_user_model
from django import forms
import re

User = get_user_model()


class RegisterForm(forms.Form):
    username        = forms.CharField(max_length=140, label='Nombre de Usuario', help_text='Mínimo 4 caracteres')
    first_name      = forms.CharField(max_length=140, label='Nombre(s)')
    last_name       = forms.CharField(max_length=140, label='Apellido(s)')
    email           = forms.EmailField(widget=forms.EmailInput)
    accept_terms    = forms.BooleanField(label='Acceptar Terminos')
    password        = forms.CharField(label='Contraseña', widget=forms.PasswordInput, help_text='Mínimo 8 caracteres')
    password2       = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('Nombre de usuario ya existe')
        if len(username) < 4:
            raise forms.ValidationError('Nombre de usuario debe ser minimo 4 caracteres')
        if not re.match(r'[A-Za-z0-9_-]+$', username):
            raise forms.ValidationError("Nombre de usuario solo puede tener letras, numeros, _ o -")
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('Contraseña debe ser mínimo de 8 caracteres')
        return password

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Contraseñas deben coincidir")
        return password2

register/views.py
from django.views.generic import TemplateView, FormView
from django.contrib.auth.models import User
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from .forms import RegisterForm
from .tasks import change_password_confirmation_mail


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'register/register.html'
    success_url = '/register/done/'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        email   = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password2')
        new_user = User.objects.create_user(
            username=username,
            first_name=first_name.title(),
            last_name=last_name.title(),
            email=email
        )
        new_user.set_password(password)
        new_user.save()
        return super().form_valid(form)


class ThanksForRegistering(TemplateView):
    template_name = 'register/register-done.html'


class UserChangePassword(PasswordChangeView):
    template_name = 'register/password_change_form.html'
    success_url = '/register/password-change/done/'

    def form_valid(self, form):
        user = self.request.user
        user_obj = User.objects.get(user)
        change_password_confirmation_mail.delay(user_obj.email)
        return super().form_valid(form)


class UserChangePasswordDone(PasswordChangeDoneView):
    template_name = 'register/password_change_done.html'


class UserPasswordReset(PasswordResetView):
    template_name = 'register/password_reset_form.html'
    success_url = '/register/reset/done/'
    email_template_name = 'register/password_reset_email.html'


class UserPasswordResetDone(PasswordResetDoneView):
    template_name = 'register/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'register/password_reset_confirm.html'
    success_url = '/register/reset-confirm/complete/'


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'register/password_reset_complete.html'

register/templates/register/password_change_done.html
{% extends 'base.html' %}

{% block content %}

    <h1>Todo Listo!</h1>
    <hr/>
    <p>La contraseña fue cambiada exitosamente!</p>
    <a class="my-3" href="{% url 'home' %}">ir a la pagina principal</a>

{% endblock %}

register/templates/register/password_change_form.html
{% extends 'base.html' %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#id_old_password").addClass("form-control my-3");
            $("#id_new_password1").addClass("form-control my-3");
            $("#id_new_password2").addClass("form-control my-3");
        })
    </script>
{% endblock %}

{% block content %}

    <h1 class="card-title">Cambiar Contraseña</h1>
    <hr/>
    {% if form.old_password.errors or form.new_password2.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for error in form.old_password.errors %}
                <li>{{ error |escape }}</li>
            {% endfor %}
            {% for error in form.new_password2.errors %}
                <li>{{ error |escape }}</li>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form method="post" action="{% url 'register:password_change' %}">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-lg-6 col-12">
                {{ form.old_password.label }} {{ form.old_password }}
                {{ form.new_password1.label }} {{ form.new_password1 }}
                {{ form.new_password2.label }} {{ form.new_password2 }}
            </div>
            <div class="col-lg-6 col-12 align-self-center">
                <span class="helptext">
                    <ul>
                        <li>Su contraseña no puede asemejarse tanto a su otra información personal.</li>
                        <li>Su contraseña debe contener al menos 8 caracteres.</li>
                        <li>Su contraseña no puede ser una clave utilizada comúnmente.</li>
                        <li>Su contraseña no puede ser completamente numérica.</li>
                    </ul>
                </span>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-12 my-3">
                <button type="submit" class="btn btn-lg btn-primary">Cambiar</button>
                <input type="hidden" name="next" value="{% url 'register:password_change_done' %}">
                <a href="{% url 'profiles:edit' request.user.username %}" class="ml-3">Regresar</a>
            </div>
        </div>
    </form>

{% endblock %}

register/templates/register/password_reset_complete.html
{% extends 'home_base.html' %}

{% load static %}

{% block content %}

    <div class="card">
        <div class="card-header text-center">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body">
            <h1 class="card-title">Contraseña nueva aceptada!</h1>
            <hr/>
            <p>Su contraseña ha sido actualizada exitosamente. Si desea puede iniciar sesión.</p>
            <a href="{% url 'login' %}">Iniciar sesión</a>
        </div>
        <div class="card-footer text-center text-muted">
            <a href="{% url 'terms' %}">Terminos</a> | <a href="{% url 'contact' %}">Contactenos</a><br/>@maca
        </div>
    </div>

{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends 'home_base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}

    <div class="card">
        <div class="card-header text-center">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body">
            <form method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-lg btn-primary">Confirmar</button>
            </form>
        </div>
        <div class="card-footer text-center text-muted">
            <a href="{% url 'terms' %}">Terminos</a> | <a href="{% url 'contact' %}">Contactenos</a><br/>@maca
        </div>
    </div>

{% endblock %}

register/templates/register/password_reset_done.html
{% extends 'home_base.html' %}

{% load static %}

{%  block content %}

    <div class="card">
        <div class="card-header text-center">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body">
            <h1>Nueva Contraseña en camino</h1>
            <hr/>
            <p>
                Le hemos mandado un correo con instrucciones, si hay una cuenta relacionada con el correo electrónico.
                Lo recibira en un par de minutos.
            </p>
            <p>
                Si no recibe el correo, asegurese que el correo este registrado con nosotros, y revise su carpeta de
                correos no deseados.
            </p>
        </div>
        <div class="card-footer text-center text-muted">
            <a href="{% url 'terms' %}">Terminos</a> | <a href="{% url 'contact' %}">Contactenos</a><br/>@maca
        </div>
    </div>

{% endblock %}

register/templates/register/password_reset_email.html
<a href="{% url 'home' %}">
    <img src="../../../static/images/nature.png" alt="null" width="512" height="512"/>
</a>
<h3>La Fogata</h3>
<hr/>
Alguien pidio una contraseña nueva para {{ email }}. As click en el link siguiente:
{{ protocol }}://{{ domain }}{% url 'register:password_reset_confirm' uidb64=uid token=token %}

<p> -La Fogata</p>

register/templates/register/password_reset_form.html
{% extends 'home_base.html' %}

{% load static %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#id_email").addClass("form-control");
        })
    </script>
{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-header text-center">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body">
            <h1 class="col">Nueva Contraseña</h1>
            <hr/>
            <p class="col">Olvido su Contraseña? Ponga su correo electronico, y le enviaremos instrucciones
                para que la actualize.</p>
            <form method="POST" action=".">{% csrf_token %}
                <div class="form-group col-lg-6 col-12">
                    {{ form.email.label }}
                    {{ form.email }}
                </div>
                <div class="col">
                    <button class="btn btn-lg btn-primary" type="submit">Enviar</button>
                </div>
            </form>
        </div>
        <div class="card-footer text-center text-muted">
            <a href="{% url 'terms' %}">Terminos</a> | <a href="{% url 'contact' %}">Contactenos</a><br/>@maca
        </div>
    </div>

{% endblock %}

register/templates/register/register-done.html
{% extends 'home_base.html' %}

{% load static %}

{% block content %}

    <div class="card text-center">
        <div class="card-header">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body">
            <h1 class="card-title">Listo!</h1>
            <hr/>
            <p class="card-text">Gracias por registrase. Inicie session y cominece a meterle leña al fuego!</p>
            <a class="card-text" href="{% url 'login' %}">Ir a la pagina de inicio</a>
        </div>
        <div class="card-footer text-muted">
            @maca
        </div>
    </div>

{% endblock %}

register/templates/register/register.html
{% extends 'home_base.html' %}

{% load static %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#id_first_name").addClass("form-control");
            $("#id_last_name").addClass("form-control");
            $("#id_email").addClass("form-control");
            $("#id_username").addClass("form-control");
            $("#id_password").addClass("form-control");
            $("#id_password2").addClass("form-control");

            var typingTimer;
            var doneInterval = 800;
            var searchInput = $('#id_username');
            var searchQuery;

            searchInput.keyup(function(event){
                searchQuery =  $(this).val()
                clearTimeout(typingTimer)
                typingTimer = setTimeout(doneSearchTyping, doneInterval)
            })

            searchInput.keydown(function(event){
                clearTimeout(typingTimer)
            })

            function doneSearchTyping(){
                if (searchQuery.length >= 4){
                    // do search
                    $.ajax({
                        url: '/api/profiles/find/' + searchQuery + '/',
                        method: 'GET',
                        success: function (data) {
                            console.log(data);
                            $('#user_check').css('display', 'none');
                        },
                        error: function (data) {
                            $('#user_check').css('display', 'inline')
                        }
                    })
                }
            }
        })
    </script>
{% endblock %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Registrarse | {{ block.super }}{% endblock %}

{% block content %}

    <div class="card mb-3 text-center">
        <div class="card-header">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <img class="card-img-top banner" src="{% static 'images/banner.jpg' %}" alt="Card image cap">
        <div class="card-body">
            <h1 class="card-title">Bienvenido!</h1>
            <small>La Fogata esta aqui para que encuentres personas
            con las cuales puedas conectarte para estar
            al dia con los acontecimientos que estan
            sucediendo en su entorno.<br/>
                Metale leña al fuego!</small>
            <hr/>

            {% if form.errors %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger alert-dismissible fade show col-6" role="alert">
                        {% for error in form.username.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                        {% for error in form.password.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                        {% for error in form.password2.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            {% endif %}

            <form method="POST" class="form">
                {% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.first_name.label }}</label>
                    <div class="col-sm-8">
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.last_name.label }}</label>
                    <div class="col-sm-8">
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form.username }}
                    </div>
                    <div class="col-sm-1 mt-1 text-left" id="user_taken_check">
                        <img src="{% static 'images/correct24x24.png' %}" id="user_check" alt="" style="display: none"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.password.label }}</label>
                    <div class="col-sm-8">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.password2.label }}</label>
                    <div class="col-sm-8">
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.accept_terms.label }}</label>
                    <div class="col-sm-8 text-sm-left mt-1">
                        {{ form.accept_terms }} <small>Al registrarse esta accediendo a los
                        <a href="#staticBackdrop" data-toggle="modal" data-target="#staticBackdrop">
                            terminos y condiciones</a> de uso</small>
                    </div>
                </div>
                <br/>
                <button class="btn btn-lg btn-primary" type="submit">Registrarse</button>

            </form>
            <div class="row my-4">
                <div class="col text-center">
                    <a href="{% url 'login' %}">Iniciar Sesión</a>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <p><a href="{% url 'terms' %}">Términos</a></p>
            <p><a href="{% url 'contact' %}">Contáctenos</a></p>
            @maca
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">La Fogata</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% include 'terms.html' %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->

{% endblock %}