accounts/api/urls.py
from django.urls import path

from tweets.api.views import TweetListAPIView

from .views import UserProfileAPIView, UsernameTakenAPIView

app_name = 'accounts'

urlpatterns = [
    path('<str:username>/', UserProfileAPIView.as_view(), name='user-profile'),
    path('<str:username>/tweet/', TweetListAPIView.as_view(), name='user-tweets'),
    path('find/<str:username>/', UsernameTakenAPIView.as_view(), name='find-user')
]

accounts/urls.py
from django.urls import path

from .views import UserDetailView, UserFollowView, user_update_view, FollowerView, FollowingView

app_name = 'accounts'

urlpatterns = [
    path('<slug:username>/', UserDetailView.as_view(), name='detail'),
    path('<slug:username>/followers/', FollowerView.as_view(), name='followers'),
    path('<slug:username>/following/', FollowingView.as_view(), name='following'),
    path('<slug:username>/edit/', user_update_view, name='edit'),
    path('<slug:username>/follow/', UserFollowView.as_view(), name='follow'),
]

register/urls.py
from django.urls import path

from .views import (
    RegisterView,
    ThanksForRegistering,
    UserChangePassword,
    UserChangePasswordDone,
    UserPasswordReset,
    UserPasswordResetDone,
    UserPasswordResetConfirmView,
    UserPasswordResetCompleteView
)

app_name = 'register'

urlpatterns = [
    path('', RegisterView.as_view(), name='start'),
    path('done/', ThanksForRegistering.as_view(), name='done'),
    path('password-change/', UserChangePassword.as_view(), name='password_change'),
    path('password-change/done/', UserChangePasswordDone.as_view(), name='password_change_done'),
    path('reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('reset/done/', UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-confirm/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

tweetme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from tweets.views import TweetListView
from tweets.api.views import SearchAPIView

from hashtags.views import HashTagView
from hashtags.api.views import HashTagAPIView

from .views import (
    UserLoginView,
    UserLogoutView,
    SearchView,
    TermsView,
    ContactFormView,
)


urlpatterns = [
    path('', TweetListView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('tweet/', include('tweets.urls', namespace='tweet')),
    path('register/', include('register.urls', namespace='register')),
    path('search/', SearchView.as_view(), name='search'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profiles/', include('accounts.urls', namespace='profiles')),
    path('api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    path('api/search/',SearchAPIView.as_view(), name='search-api'),
    path('api/tag/<str:hashtag>/',HashTagAPIView.as_view(), name='tag-api'),
    path('api/profiles/', include('accounts.api.urls', namespace='profile-api')),
    path('tags/<str:hashtag>/', HashTagView.as_view(), name='hashtag'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    TweetDetailView,
    TweetListView,
    TweetCreateView,
    # TweetUpdateView,
    TweetDeleteView,
    RetweetView,
)

app_name = 'tweets'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/update/', TweetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TweetDeleteView.as_view(), name='delete'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),

]

accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

from .utils import upload_image_path


class UserProfileManager(models.Manager):
    use_for_related_fields = True

    def random(self):
        qs = self.get_queryset().all()
        try:
            if self.instance:
                qs = qs.exclude(user=self.instance)
        except:
            pass
        return qs.order_by("?")

    def all(self):
        qs = self.get_queryset().all()
        try:
            if self.instance:
                qs = qs.exclude(user=self.instance)
        except:
            pass
        return qs

    def toggle_follow(self, user, to_toggle_user):
        user_profile = UserProfile.objects.get(user=user)
        if to_toggle_user in user_profile.following.all():
            user_profile.following.remove(to_toggle_user)
            added = False
        else:
            user_profile.following.add(to_toggle_user)
            added = True
        return added

    def is_following(self, user, followed_by_user):
        user_profile = UserProfile.objects.get(user=user)
        if followed_by_user in user_profile.following.all():
            return True
        return False


class UserProfile(models.Model):
    user            = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
    image           = models.ImageField(upload_to=upload_image_path,
                                    blank=True,
                                    null=True)
    following       = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='followed_by')

    objects = UserProfileManager()

    def __str__(self):
        return self.user.username

    def get_following(self):
        return self.following.all().exclude(username=self.user.username)

    def get_follow_url(self):
        return reverse_lazy('profiles:follow', kwargs={'username': self.user.username})

    def get_absolute_url(self):
        return reverse_lazy('profiles:detail', kwargs={'username': self.user.username})

    # def save(self, *args, **kwargs):
    #     if self.image:
    #         rotate_image(self)
    #     return super().save(*args, **kwargs)

accounts/forms.py
from django import forms

from .models import UserProfile


class UserUpdateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = self.request.user.first_name
        self.fields['last_name'].widget.attrs['placeholder'] = self.request.user.last_name
        self.fields['email'].widget.attrs['placeholder'] = self.request.user.email

    first_name  = forms.CharField(label='Nombre', max_length=40, required=False)
    last_name   = forms.CharField(label='Apellido', max_length=40, required=False)
    image       = forms.ImageField(label='Imagen', allow_empty_file=True, required=False)
    email       = forms.EmailField(required=False)
    delete     = forms.CharField(label='Eliminar cuenta?', max_length=7, required=False)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        print(email)
        return email

    def clean(self):
        data = self.cleaned_data
        f_name  = data.get('first_name')
        l_name  = data.get('last_name')
        img     = data.get('image')
        email = data.get('email')
        delete = data.get('delete').lower()
        u = self.request.user
        user_prof = UserProfile.objects.get(user__username=u)
        if f_name != '':
            user_prof.user.first_name = f_name.title()
        if l_name != '':
            user_prof.user.last_name = l_name.title()
        if email != '':
            user_prof.user.email = email
        if img is not None:
            user_prof.image = img
        if delete == 'borrar':
            user_prof.user.active = False

        user_prof.save()

        return data

accounts/api/views.py
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.generics import RetrieveAPIView
from django.contrib.auth.models import User

from .serializers import UserDisplaySerializer, UsernameTakenSerializer


class UserProfileAPIView(RetrieveAPIView):
    queryset                = User.objects.all()
    lookup_field            = 'username'
    serializer_class        = UserDisplaySerializer
    permission_classes      = [IsAuthenticated]


class UsernameTakenAPIView(RetrieveAPIView):
    queryset                = User.objects.all()
    lookup_field            = 'username'
    serializer_class        = UsernameTakenSerializer
    permission_classes      = [AllowAny]

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404, render
from django.views.generic import DetailView, View
from django.contrib.auth import get_user_model
from django.contrib import messages

from .forms import UserUpdateForm

from .models import UserProfile

User = get_user_model()


class FollowingView(LoginRequiredMixin, DetailView):
    template_name   = 'accounts/following.html'
    slug_url_kwarg  = 'username'
    slug_field      = 'username'
    model           = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        following = UserProfile.objects.is_following(self.request.user, self.get_object())
        context['following'] = following
        return context


class FollowerView(LoginRequiredMixin, DetailView):
    template_name   = 'accounts/followers.html'
    slug_url_kwarg  = 'username'
    slug_field      = 'username'
    model           = User


class UserDetailView(LoginRequiredMixin, DetailView):
    template_name   = 'accounts/user_detail.html'
    slug_url_kwarg  = 'username'
    slug_field      = 'username'
    model           = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        following = UserProfile.objects.is_following(self.request.user, self.get_object())
        context['following'] = following
        return context


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, username):
        toggle_user = get_object_or_404(User, username__iexact=username)
        UserProfile.objects.toggle_follow(request.user, toggle_user)
        return redirect("profiles:detail", username=username)


def user_update_view(request, *args, **kwargs):
    username = kwargs.get('username')
    if request.user.username != username:
        messages.add_message(request, messages.ERROR, 'No tiene permitido acceso')
        return redirect('profiles:detail', username=request.user.username)
    template = 'accounts/user_update.html'
    user = UserProfile.objects.get(user__username=username)
    form = UserUpdateForm(request.POST or None, request.FILES or None, request=request)
    context = {
        'user_img': user.image,
        'form': form
    }
    try:
        if form.is_valid():
            return redirect('profiles:detail', username=username)
    except OSError:
        return redirect('profiles:detail', username=username)
    except AttributeError:
        return redirect('profiles:detail', username=username)
    return render(request, template, context)

accounts/templates/accounts/followers.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-3 col-12" id="user-container" data-url="/api/profiles/{{ object.username }}">
            <img src="{{ object.profile.image.url }}" class="mr-3 mb-3" alt="{{ object.username }}" style="max-height: 200px; max-width: 200px">
            <h1>{{ object.username }}</h1>
            <p>{{ object.first_name }} {{ object.last_name }}</p>

        </div>
        <div class="col-lg-6 col-12">
            <h1>Seguidores <small>{{ object.followed_by.all.count }}</small></h1>
            <br/>
            {% for profile in object.followed_by.all %}
                <div class="media">
                    <img src="{{ profile.image.url }}" class="mr-3" alt="null" style="height: 48px; width: 48px">
                    <div class="media-body">
                        <a href="/profiles/{{ profile.user.username }}">@{{ profile.user.username }}</a><br/>
                        {{ profile.user.first_name }} {{ profile.user.last_name }}
                    </div>
                </div>
                <hr/>
            {% empty %}
                <h6>No tiene seguidores.</h6>
            {% endfor %}

        </div>
    </div>

{% endblock %}

accounts/templates/accounts/following.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-3 col-12" id="user-container" data-url="/api/profiles/{{ object.username }}">
            <img src="{{ object.profile.image.url }}" class="mr-3 mb-3" alt="{{ object.username }}" style="max-height: 200px; max-width: 200px">
            <h1>{{ object.username }}</h1>
            <p>{{ object.first_name }} {{ object.last_name }}</p>

        </div>
        <div class="col-lg-6 col-12">
            <h1>Siguiendo <small>{{ object.profile.get_following.count }}</small></h1>
            <br/>
            {% for user in object.profile.get_following %}
                <div class="media">
                    <img src="{{ user.profile.image.url }}" class="mr-3" alt="null" style="height: 48px; width: 48px">
                    <div class="media-body">
                        <a href="/profiles/{{ user.username }}">@{{ user.username }}</a><br/>
                        {{ user.first_name }} {{ user.last_name }}
                    </div>
                </div>
                <hr/>
            {% empty %}
                <h6>No sigue a nadie.</h6>
            {% endfor %}

        </div>
    </div>

{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{% load static %}

{% block script %}

    <script>

        $(document).ready(function () {
            loadTweetContainer("tweet-container");
        });

    </script>

{% endblock %}

{% block title %}Perfil | {{ block.super }}{% endblock %}

{% block content %}

    {% if messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for message in messages %}
                <strong>Oh no! </strong>{{ message|escape }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-lg-3 col-12" id="user-container" data-url="/api/profiles/{{ object.username }}">
            {% if object.profile.image %}
                <img src="{{ object.profile.image.url }}" class="mr-3 mb-3" alt="" style="max-height: 200px; max-width: 200px">
            {% else %}
                <img src="{% static 'images/default_avatar.jpg' %}" class="mr-3 mb-3" alt="" style="max-height: 200px; max-width: 200px">
            {% endif %}
            <h1>{{ object.username }}</h1>
            <p>{{ object.first_name }} {{ object.last_name }}</p>
            <hr/>
            <p>{{ object.followed_by.all.count }}{% if object.followed_by.all.count == 1 %} Seguidor{% else %} Seguidores{% endif %}</p>
            <p>
                {% if object != request.user %}
                    <a href="{% url 'profiles:follow' username=object.username %}">
                        {% if following %}No seguir mas{% else %}Seguir{% endif %}
                    </a>
                {% endif %}
            </p>

            <a class="btn-link" href="{% url 'profiles:following' object.username %}">
                <h3>Siguiendo <small>{{ object.profile.get_following.count }}</small></h3></a>
            {% for user in object.profile.get_following|slice:":4" %}
                <a href="/profiles/{{ user.username }}">
                    {% if user.profile.image %}
                        <img src="{{ user.profile.image.url }}" class="avatar" alt=""/>
                    {% else %}
                        <img src="{% static 'images/default_avatar.jpg' %}" class="avatar" alt=""/>
                    {% endif %}
                </a>
            {% empty %}
                <h6>No sigue a nadie.</h6>
            {% endfor %}

            <hr/>
            <a class="btn-link" href="{% url 'profiles:followers' object.username %}">
                <h3>Seguidores</h3></a>
            {% for profile in object.followed_by.random|slice:":4" %}
                <a href="/profiles/{{ profile.user.username }}">
                    {% if profile.image %}
                        <img src="{{ profile.image.url }}" class="avatar" alt=""/>
                    {% else %}
                        <img src="{% static 'images/default_avatar.jpg' %}" class="avatar" alt=""/>
                    {% endif %}
                </a>
            {% empty %}
                <h6>No tiene seguidores.</h6>
            {% endfor %}
            <hr/>

            <div class="text-center">
                <small>
                    {% if object == request.user %}
                        <a href="{% url 'profiles:edit' object.username %}" style="color: darkseagreen"><u>Editar perfil</u></a>
                    {% endif %}
                </small>
            </div>

        </div>
        <div class="col-lg-7 col-12">
            <h1>Actividad</h1>
            <div id="tweet-container" data-url="/api/profiles/{{ object.username }}/tweet/">

            </div>
            <a href="#" id="loadMore">cenizas..</a>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/user_register.html
{% extends 'home_base.html' %}

{% load static %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#id_username").addClass("form-control");
            $("#id_first_name").addClass("form-control");
            $("#id_last_name").addClass("form-control");
            $("#id_email").addClass("form-control");
        })
    </script>
{% endblock %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Registrarse | {{ block.super }}{% endblock %}

{% block content %}

    <div class="card mb-3 text-center">
        <div class="card-header">
            Logo
        </div>
        <img class="card-img-top banner" src="{% static 'images/banner.jpg' %}" alt="Card image cap">
        <div class="card-body">
            <h1 class="card-title">Bienvenido!</h1>
            <small>Deno esta aqui para que encuentres personas
            con las cuales puedas conectarte para estar
            al dia con los acontecimientos que estan
            sucediendo en su entorno.<br/>
                Metale leña al fuego!</small>
            <hr/>
            <form method="POST" class="form" action=".">
                {% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.first_name.label }}</label>
                    <div class="col-sm-8">
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.last_name.label }}</label>
                    <div class="col-sm-8">
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ form.accept_terms.label }}</label>
                    <div class="col-sm-8 text-sm-left mt-1">
                        {{ form.accept_terms }}
                    </div>
                </div>
                <br/>
                <button class="btn btn-lg btn-primary" type="submit">Registrarse</button>

            </form>
            <div class="row my-4">
                <div class="col text-center">
                    <a href="{% url 'login' %}">Iniciar Sesión</a>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            @maca
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/user_update.html
{% extends 'base.html' %}

{% block script %}
    <script>
        $('#id_first_name').addClass('form-control');
        $('#id_last_name').addClass('form-control');
        $('#id_email').addClass('form-control');
        $('#id_delete').addClass('form-control');
    </script>
{% endblock %}

{% block title %}Editar | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row text-center">
        <div class="col-lg-3"></div>
        <div class="col-12 col-lg-6">
            <h1>Actualize su Perfil</h1>
            <hr/>
        </div>
        <div class="col-lg-3"></div>
    </div>

    <form class="form mt-3" method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row text-center">
            <div class="col-lg-3"></div>
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <label for="firstName">{{ form.first_name.label }}</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="lastName">{{ form.last_name.label }}</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="emailLink">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="imageURL">{{ form.image.label }}</label><br/>
                    {% if user_img %}
                        <img src="{{ user_img.url }}" class="align-self-center mr-3" style="height: 64px; width: 64px" alt="">
                    {% endif %}
                    {{ form.image }}
                </div>
                <div class="form-group">
                    <a href="{% url 'register:password_change' %}">Cambiar la Contraseña</a>
                </div>
                <div class="form-group">
                    <h1>Eliminar</h1>
                    <hr/>
                    <label for="deleteBox">{{ form.delete.label }}</label><br/>
                    {{ form.delete }}
                    <small>si desea eliminar su cuenta escriba 'borrar'?</small>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
        <div class="row text-center my-5">
            <div class="col-lg-6">
                <a href="{% url 'profiles:detail' request.user.username %}">Regresar</a>
            </div>
            <div class="col-lg-6">
                <button class="btn btn-warning" type="submit">Actualizar</button>
            </div>
        </div>
    </form>


{% endblock %}