register/urls.py
from django.urls import path

from .views import (
    RegisterView,
    ThanksForRegistering,
    UserChangePassword,
    UserChangePasswordDone,
    UserPasswordReset,
    UserPasswordResetDone,
    UserPasswordResetConfirmView,
    UserPasswordResetCompleteView
)

app_name = 'register'

urlpatterns = [
    path('', RegisterView.as_view(), name='start'),
    path('done/', ThanksForRegistering.as_view(), name='done'),
    path('password-change/', UserChangePassword.as_view(), name='password_change'),
    path('password-change/done/', UserChangePasswordDone.as_view(), name='password_change_done'),
    path('reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('reset/done/', UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-confirm/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

tweetme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from tweets.views import TweetListView
from tweets.api.views import SearchAPIView

from hashtags.views import HashTagView
from hashtags.api.views import HashTagAPIView

from .views import (
    UserLoginView,
    UserLogoutView,
    SearchView,
    TermsView,
    ContactFormView,
)


urlpatterns = [
    path('', TweetListView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('tweet/', include('tweets.urls', namespace='tweet')),
    path('register/', include('register.urls', namespace='register')),
    path('search/', SearchView.as_view(), name='search'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profiles/', include('accounts.urls', namespace='profiles')),
    path('api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    path('api/search/',SearchAPIView.as_view(), name='search-api'),
    path('api/tag/<str:hashtag>/',HashTagAPIView.as_view(), name='tag-api'),
    path('api/profiles/', include('accounts.api.urls', namespace='profile-api')),
    path('tags/<str:hashtag>/', HashTagView.as_view(), name='hashtag'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    TweetDetailView,
    TweetListView,
    TweetCreateView,
    # TweetUpdateView,
    TweetDeleteView,
    RetweetView,
)

app_name = 'tweets'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/update/', TweetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TweetDeleteView.as_view(), name='delete'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Website favicon -->
    <link rel="icon" type="image/png" href='{% static "favicon/favicon-16x16.png" %}' sizes="16x16" />

    <title> {% block title %}Fogata{% endblock %}</title>

</head>
<body style="background-image: url({% static 'images/background.jpg' %})">
    {% load static %}
    {% include 'navbar.html' %}

    <script>
        var myApp = {
            staticUrl: '{% static 'images' %}'
        }
    </script>

    <div class="container my-4">
        <div class="card" id="card-container-body">
            <div id="customAlertContainer"></div>
            {% block content %}

            {% endblock %}
        </div>
    </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'js/tweetme.custom.js' %}"></script>
    {% block script %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<noscript>Su navegador no soporta javascript</noscript>
</body>
<footer class="text-right p-2">
    <a href="{% url 'terms' %}" id="btn-footer-link">Términos</a><br/>
    <a href="{% url 'contact' %}" id="btn-footer-link">Contáctenos</a><br/>
    <span>@maca</span>
</footer>
</html>

templates/contact.html
{%  extends 'home_base.html' %}

{% load static %}

{% load crispy_forms_filters %}

{%  load crispy_forms_tags %}

{% block head_title %}Contáctenos | {{ block.super }}{% endblock %}

{% block content %}

    <div class="card text-center">
        <div class="card-header">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body container col-lg-6">

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message|escape }}
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

            <h1>Contactenos</h1>
            <hr/>
            <p class="text-muted">Preguntas, sugerencias, comentarios, reportes?</p>
            <p class="text-muted">No dude en escribirnos!</p>
            <hr/>

            <form method="post" action=".">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-lg btn-success my-2">Enviar</button>
            </form>

            <br/>

            {% if previous_url %}
                <p><a class='my-5' href={{ previous_url }}>Regresar</a></p>
            {% endif %}
            <p><a href="{% url 'home' %}">Inicio</a></p>

        </div>
        <div class="card-footer text-muted">
            <p><a href="{% url 'terms' %}">Términos</a></p>
            <p>@maca</p>
        </div>
    </div>

{% endblock %}

templates/home_base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Website favicon -->
    <link rel="icon" type="image/png" href='{% static "favicon/favicon-16x16.png" %}' sizes="16x16" />

    <style>
        #parent {
            padding: 4% 1%;
        }
        #child {
            padding: 8% 1%;
        }
    </style>
    <title> {% block title %}Fogata{% endblock %}</title>
</head>
<body style="background-image: url({% static 'images/background.jpg' %})">

    <div class="container">
        <div class="col my-4 align-self-center">
            {% block content %}

            {% endblock %}
        </div>
    </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    {% block script %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<noscript>Su navegador no soporta Javascript!</noscript>
</body>
</html>

templates/login.html
{% extends "home_base.html" %}

{% load static %}

{% block script %}
<script>
$(document).ready(function () {
    $("#id_username").addClass("form-control");
    $("#id_password").addClass("form-control");
})
</script>
{% endblock %}

{% block content %}

    <div class="card text-center">
        <div class="card-header">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="row no-gutters">
            <div class="card-body">
                <h2 class="card-title">La Fogata</h2>
                <hr/>
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div style="padding: 3%">
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        <div class="row text-center">
                            <div class="col-lg-3"></div>
                            <div class="form-group col-lg-6">
                                {{ form.username.label_tag }}<br>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-3"></div>
                            <br/>
                            <div class="col-lg-3"></div>
                            <div class="form-group col-lg-6">
                                {{ form.password.label_tag }}<br>
                                {{ form.password }}
                            </div>
                            <div class="col-lg-3"></div>
                            <br/>
                            <div class="col-lg-3"></div>
                            <div class="col-lg-6 mt-3">
                                <button type="submit" class="btn btn-block btn-primary">Inicar Sesión</button>
                                <input type="hidden" name="next" value="{% url 'home' %}">
                            </div>
                            <div class="col-lg-3"></div>
                        </div>
                    </form>
                </div>
                {# Assumes you setup the password_reset view in your URLconf #}
                <p><a href="{% url 'register:start' %}">Registrarse</a></p>
                <p><a href="{% url 'register:password_reset' %}">Olvidé mi contraseña?</a></p>
            </div>
        </div>
        <div class="card-footer">
            <p><a href="{% url 'terms' %}">Términos</a></p>
            <p><a href="{% url 'contact' %}">Contáctenos</a></p>
            @maca
        </div>
    </div>

{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'images/nature.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <b>Fogata</b>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ request.user.profile.get_absolute_url }}">Perfil
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
            </li>
        </ul>
        {% include 'tweets/search_form.html' %}
    </div>
</nav>

templates/search_view.html
{% extends 'base.html' %}

{% load static %}

{% block script %}

    <script>

        $(document).ready(function () {
            loadTweetContainer("tweet-container");
        });

    </script>

{% endblock %}

{% block title %}Búsqueda | {{ block.super }}{% endblock %}

{% block content %}
    <div class="row" id="row1">
        <div class="col-sm-12">
            {% if request.GET.q %}
            <p class="lead">Resultados: {{ request.GET.q }}</p>
            <hr/>
            {% endif %}
        </div>
        <div class="col-lg-9 col-12">
            <h1>Leñas</h1>
            <hr/>
            <div id="tweet-container" data-url="/api/search/" class="text-center">

            </div>
            <a href="#" id="loadMore">cenizas..</a>
        </div>
        <div class="col-lg-3 col-12">
            <h1>Usuarios</h1>
            <hr/>
            {% for user in users %}
                {% if user.profile.image %}
                    <img src="{{ user.profile.image.url }}" class="avatar mr-2" alt=""/>
                {% else %}
                    <img src="{% static 'images/default_avatar.jpg' %}" class="avatar mr-2" alt=""/>
                {% endif %}
                <a href="/profiles/{{ user.username }}/">{{ user.username }}</a><br/>
            {% empty %}
                <p>No se encontro a ningun usuario</p>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/terms.html
<h1 class="text-center">Terminos y Condiciones de Uso</h1>
<hr/>
<p>Puede usar nuestra plataforma para expresar sus ideas sin censura al menos que sean en forma de ataque
    personal contra otro usuario.</p>
<p>Nos reservamos el derecho de eliminar a cualquier usuario que utilize los siguientes tópicos como
    ataque personal y/o prejuicio:</p>
<ul>
    <li>Racismo</li>
    <li>Sexismo</li>
    <li>Nacionalidad</li>
    <li>Clase social</li>
</ul>
<p>Además de cualquier otro modo de prejuicio que los moderadores de LaFogata.biz
    decidan sea considerada una ofensa intelectual.</p>
<p>Nos dedicamos a proveer una plataforma en la cual todo usuario es libre de
    expresarse de la forma que desee.</p>

<h1>Privacidad</h1>
<hr/>
<p>No venderemos ni compartiremos su información sin su autorización.</p>
<p>Cada usuario es considerado un "autor", y solo las publicaciones hechas por
    el mismo son tratadas de forma pública.</p>
<p>Se le motiva a todos nuestros usuarios a usar su libre derecho de expresión,
    con excepcion en situaciones en las que algún usuario
    quiebre alguna de las reglas previamente establecidas por la cual el
    acceso será revocado.</p>
<hr/>

<h3>Gracias y disfrute de nuestros servicios</h3><br/>

templates/terms_base.html
{% extends 'home_base.html' %}

{% load static %}

{% block head_title %}Términos | {{ block.super }}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header text-center">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/nature.png' %}" width="32" height="32" alt="Fogata">
            </a>
        </div>
        <div class="card-body container col-lg-6">

            {% include 'terms.html' %}

            {% if previous_url %}
                <p><a class="my-3" href={{ previous_url }}>Regresar</a></p>
            {% endif %}
            <p><a href="{% url 'home' %}">Inicio</a></p>

        </div>
        <div class="card-footer text-center">
            <p><a href="{% url 'contact' %}">Contáctenos</a></p>
            <p>@maca</p>
        </div>
    </div>
{% endblock %}

templates/thanks.html
{% extends 'home_base.html' %}

{% load static %}


{% block content %}

    <div class="card text-center">
        <div class="card-header">
            logo
        </div>
        <div class="card-body">
            <h1 class="card-title">Listo!</h1>
            <hr/>
            <p class="card-text">Gracias por registrase. Inicie session y descubra el fuego al que le estan metiendo leña!</p>
            <a class="card-text" href="{% url 'login' %}">Ir a la pagina de inicio</a>
        </div>
        <div class="card-footer text-muted">
            @maca
        </div>
    </div>

{% endblock %}